---
title: "data_wrangling2"
author: "Manye Dong"
date: "2023-10-12"
output: github_document
---

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
drug_use_html = read_html(url)

drug_use_html
```
```{r}
table_marj = 
  drug_use_html |> 
  html_table() |> 
  # only want the first of all 15 tables
  first() |>
  # minus the first row here
  slice(-1)

table_marj
```
Learning Assessment
```{r}
NY_living = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"
NY_living_html = read_html(NY_living)

NY_living_html
```
```{r}
NY_living_html |> 
  html_table(header = TRUE) |>
  first()
```

Web Scraper
```{r}
# import Star Wars
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```

```{r}
title_vec = 
  swm_html |>
  # specifying the CSS tag for the elements
  html_elements(".lister-item-header a") |>
  html_text()

gross_rev_vec = 
  swm_html |>
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |>
  html_text()

runtime_vec = 
  swm_html |>
  html_elements(".runtime") |>
  html_text()
```

```{r}
swm_df = 
  tibble(
    title = title_vec,
    rev = gross_rev_vec,
    runtime = runtime_vec)
```

